name: ${project.name}
main: net.daboross.bukkitdev.devtest.DevTestPlugin
version: ${project.version}
author: Dabo Ross
description: ${project.description}
url: ${project.url}
soft-depend: [SkyWars]
commands:
  dev: